-- ============================================
-- COPY THIS INTO: https://app.supabase.com → SQL Editor → New Query → RUN
-- DISABLES RLS ON ALL ACTUAL TABLES (skips views)
-- ============================================

-- Disable RLS on ALL actual tables (not views)
ALTER TABLE IF EXISTS public.analysis_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.chat_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.chat_rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.chat_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.coach_achievements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.coach_education DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.coach_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.coach_specialties DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.coach_statistics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.connection_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.connections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.direct_chat_connections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.focus_areas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.motion_analysis_annotations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.motion_analysis_frames DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.motion_analysis_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.motion_analysis_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.performance_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pricing DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.specialty_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sports DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.survey_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.users_subscription DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.video_coaches DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.video_feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.videos DISABLE ROW LEVEL SECURITY;

-- Verify all RLS is disabled
SELECT tablename, rowsecurity FROM pg_tables 
WHERE schemaname = 'public'
ORDER BY tablename;
